// Shared domain types for the CodeSage web AI agent.

export type Role = "user" | "assistant";

export interface ToolCall {
  id: string;
  toolName: string;
  args: Record<string, unknown>;
  result?: string;
  status: "executing" | "success" | "error";
}

export interface Primitive3D {
  type: "box" | "sphere" | "cylinder" | "cone" | "torus" | "tree";
  color?: string;
  position?: [number, number, number];
  scale?: [number, number, number];
}

export interface Model3DData {
  title: string;
  primitives: Primitive3D[];
  blenderScript: string;
}

export interface ChatMessage {
  id: string;
  role: Role;
  content: string;
  createdAt: number;
  /** Optional intermediate "thinking" steps the agent took. */
  reasoning?: string[];
  /** Optional tool execution trace for agentic actions. */
  toolsUsed?: ToolCall[];
  /** Optional embedded 3D scene data generated by Blender agentic tool. */
  model3D?: Model3DData;
}

export interface Conversation {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

/** A capability the agent advertises in the UI. */
export interface AgentSkill {
  id: string;
  label: string;
  description: string;
  icon: string;
}

export type ProviderPreset = "openai" | "groq" | "ollama" | "openrouter" | "custom";

export interface AgentSettings {
  useRemote: boolean;
  provider: ProviderPreset;
  baseUrl: string;
  apiKey: string;
  model: string;
}
